sudo: required
dist: trusty

language: python

python:
  - "3.7"

branches:
  only:
  - master
  
services:
  - docker
  
before_install:
  - docker build --tag=arrests .

script:
  - /app/arrests.sh
