sudo: required
dist: trusty

language: python

python:
  - "3.6"

branches:
  only:
  - master
  
services:
  - docker
  
before_install:
  - docker build --tag=arrests .

script:
  - docker run --rm -e GITHUB_USER=$var1 -e GITHUB_KEY=$var2 --volume "/home/travis/dcso_arrests/:/data" arrests
